---
services:
  - name: hcc-example
    type: container
    build:
      repo: https://github.com/huma-engineering/hcloud-test
      branch: main
      dockerfile: Dockerfile
      context: .
    ingress:
      host: cli-test.sbx.huma.com
      paths: ["/"]
      port: 8000
