on:
  push:
    branches:
      - openclaw

workspace:
  id: 2
  name: production-test
  project: openclaw

services:
  - name: gateway
    type: container
    build:
      repo: https://github.com/huma-engineering/fastapi-example
      branch: openclaw
      dockerfile: Dockerfile
      context: .
    replicas: 1
    ingress:
      paths: ["/"]
      port: 18789
      ipAllowList:
        - source: 79.173.128.242/32
          description: "London Office"
    command:
      start: /entrypoint.sh
    envs:
      - type: secret
        name: openclaw-secrets
      - type: configmap
        name: openclaw-custom